#!/usr/bin/env bash

# 1Password Secrets Sync Script
# This script fetches secrets from 1Password and creates a local .secrets file
# that can be sourced by your shell

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
DOTFILES_DIR="${HOME}/workspace/dotfiles"
TEMPLATE_FILE="${DOTFILES_DIR}/home/.secrets.template"
OUTPUT_FILE="${HOME}/.secrets"
TEMP_FILE="${OUTPUT_FILE}.tmp"

# AWS Config
AWS_CONFIG_OP_REFERENCE="op://Work/AWS config/config"  # 1Password reference for AWS config
AWS_CONFIG_OUTPUT="${HOME}/.aws/config"
AWS_CONFIG_TEMP="${AWS_CONFIG_OUTPUT}.tmp"

# Function to print colored output
print_message() {
    local color=$1
    shift
    echo -e "${color}$*${NC}"
}

# Check if 1Password CLI is installed
if ! command -v op &> /dev/null; then
    print_message "$RED" "Error: 1Password CLI (op) is not installed."
    print_message "$YELLOW" "Install it with: brew install --cask 1password-cli"
    exit 1
fi

# Check if template file exists
if [[ ! -f "$TEMPLATE_FILE" ]]; then
    print_message "$RED" "Error: Template file not found at $TEMPLATE_FILE"
    exit 1
fi

# Check if user is signed in to 1Password
if ! op account list &> /dev/null; then
    print_message "$YELLOW" "Not signed in to 1Password. Attempting to sign in..."
    if ! eval $(op signin); then
        print_message "$RED" "Error: Failed to sign in to 1Password"
        exit 1
    fi
fi

print_message "$GREEN" "Fetching secrets from 1Password..."

# Create header for output file
cat > "$TEMP_FILE" << 'EOF'
#!/usr/bin/env bash
# 1Password Secrets - Auto-generated
# DO NOT EDIT THIS FILE DIRECTLY - Edit .secrets.template instead
# Generated: $(date)
#
# This file contains sensitive information and should NEVER be committed to git

EOF

# Process the template file
while IFS= read -r line; do
    # Skip comments and empty lines
    if [[ "$line" =~ ^#.*$ ]] || [[ -z "$line" ]]; then
        continue
    fi
    
    # Check if line contains an export statement with op:// reference
    if [[ "$line" =~ ^export[[:space:]]+([A-Z_][A-Z0-9_]*)=\"(op://.*)\"$ ]]; then
        var_name="${BASH_REMATCH[1]}"
        op_reference="${BASH_REMATCH[2]}"
        
        print_message "$YELLOW" "  Fetching $var_name..."
        
        # Try to fetch the secret from 1Password
        if secret_value=$(op read "$op_reference" 2>/dev/null); then
            # Escape special characters in the secret value
            escaped_value=$(printf '%q' "$secret_value")
            echo "export ${var_name}=\"${escaped_value}\"" >> "$TEMP_FILE"
            print_message "$GREEN" "    ✓ $var_name fetched successfully"
        else
            print_message "$RED" "    ✗ Failed to fetch $var_name (reference: $op_reference)"
            echo "# export ${var_name}=\"FAILED_TO_FETCH\"" >> "$TEMP_FILE"
        fi
    fi
done < "$TEMPLATE_FILE"

# Add footer
cat >> "$TEMP_FILE" << 'EOF'

# Function to verify secrets are loaded
verify_secrets() {
    echo "Loaded secrets:"
    env | grep -E '^(GITLAB_|GITHUB_|AWS_|DB_|API_|SSH_)' | sed 's/=.*/=<hidden>/' | sort
}

# Confirmation that secrets were loaded
if [[ -n "${SECRETS_LOADED:-}" ]]; then
    echo "Secrets already loaded"
    echo "run 'verify_secrets' to list loaded secrets"
else
    export SECRETS_LOADED=1
    echo "Secrets loaded from 1Password (run 'verify_secrets' to list)"
fi
EOF

# Move temp file to final location
mv "$TEMP_FILE" "$OUTPUT_FILE"
chmod 600 "$OUTPUT_FILE"

print_message "$GREEN" "✓ Secrets file created at $OUTPUT_FILE"
print_message "$YELLOW" "Add 'source ~/.secrets' to your shell configuration to use these secrets"

# Optional: Show what was loaded (without values)
echo ""
print_message "$GREEN" "Secrets available:"
grep "^export" "$OUTPUT_FILE" | sed 's/export \([^=]*\)=.*/  - $\1/' || true

# Process AWS Config from 1Password
print_message "$GREEN" "Fetching AWS config from 1Password..."

# Ensure .aws directory exists
mkdir -p "$(dirname "$AWS_CONFIG_OUTPUT")"

# Check if AWS config already exists and prompt for overwrite
if [[ -f "$AWS_CONFIG_OUTPUT" ]]; then
    print_message "$YELLOW" "AWS config file already exists at $AWS_CONFIG_OUTPUT"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo    # Move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_message "$YELLOW" "Skipping AWS config update"
    else
        # Try to fetch AWS config from 1Password
        if aws_config_content=$(op read "$AWS_CONFIG_OP_REFERENCE" 2>/dev/null); then
            # Create header for AWS config
            cat > "$AWS_CONFIG_TEMP" << EOF
# AWS Config - Auto-generated from 1Password
# DO NOT EDIT THIS FILE DIRECTLY - Edit the AWS config item in 1Password instead
# Generated: $(date)
#
# This file contains AWS configuration and should NEVER be committed to git

EOF
    
            # Add the content from 1Password
            echo "$aws_config_content" >> "$AWS_CONFIG_TEMP"
            
            # Move temp file to final location
            mv "$AWS_CONFIG_TEMP" "$AWS_CONFIG_OUTPUT"
            chmod 600 "$AWS_CONFIG_OUTPUT"
            
            print_message "$GREEN" "✓ AWS config updated at $AWS_CONFIG_OUTPUT"
            print_message "$YELLOW" "Edit the 'AWS config' item in 1Password to update your AWS profiles"
        else
            print_message "$RED" "✗ Failed to fetch AWS config from 1Password (reference: $AWS_CONFIG_OP_REFERENCE)"
            print_message "$YELLOW" "Create an item called 'AWS config' in your Private vault with your AWS configuration"
        fi
    fi
else
    # File doesn't exist, create it without prompting
    if aws_config_content=$(op read "$AWS_CONFIG_OP_REFERENCE" 2>/dev/null); then
        # Create header for AWS config
        cat > "$AWS_CONFIG_TEMP" << EOF
# AWS Config - Auto-generated from 1Password
# DO NOT EDIT THIS FILE DIRECTLY - Edit the AWS config item in 1Password instead
# Generated: $(date)
#
# This file contains AWS configuration and should NEVER be committed to git

EOF
        
        # Add the content from 1Password
        echo "$aws_config_content" >> "$AWS_CONFIG_TEMP"
        
        # Move temp file to final location
        mv "$AWS_CONFIG_TEMP" "$AWS_CONFIG_OUTPUT"
        chmod 600 "$AWS_CONFIG_OUTPUT"
        
        print_message "$GREEN" "✓ AWS config created at $AWS_CONFIG_OUTPUT"
        print_message "$YELLOW" "Edit the 'AWS config' item in 1Password to update your AWS profiles"
    else
        print_message "$RED" "✗ Failed to fetch AWS config from 1Password (reference: $AWS_CONFIG_OP_REFERENCE)"
        print_message "$YELLOW" "Create an item called 'AWS config' in your Private vault with your AWS configuration"
        
        # Create a fallback template
        cat > "$AWS_CONFIG_OUTPUT" << 'EOF'
# AWS Config - Fallback template
# Create an 'AWS config' item in 1Password with your actual configuration

[default]
region = us-east-1
output = json

# Add your AWS profiles here
# [profile work-dev]
# region = us-east-1
# sso_start_url = https://your-org.awsapps.com/start
# sso_region = us-east-1
# sso_account_id = 123456789012
# sso_role_name = DeveloperRole
EOF
        chmod 600 "$AWS_CONFIG_OUTPUT"
        print_message "$YELLOW" "Created fallback template at $AWS_CONFIG_OUTPUT"
    fi
fi